// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApw8WHmdFlCZdiqMVaaSciqtc3RVS51Hc',
    appId: '1:173959701132:web:077e0035be5790ef8111a9',
    messagingSenderId: '173959701132',
    projectId: 'pocket-doctor-b5458',
    authDomain: 'pocket-doctor-b5458.firebaseapp.com',
    databaseURL: 'https://pocket-doctor-b5458-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pocket-doctor-b5458.firebasestorage.app',
    measurementId: 'G-MYPZ4GHBCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoK4HX46UrhyWgAg2W_RXSvsUV3lWtbN0',
    appId: '1:173959701132:android:293c887dd0cfde498111a9',
    messagingSenderId: '173959701132',
    projectId: 'pocket-doctor-b5458',
    databaseURL: 'https://pocket-doctor-b5458-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pocket-doctor-b5458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhMSVNIop58coXhZpOS5KdljKgmdhUPQ',
    appId: '1:173959701132:ios:8da34154713a7cea8111a9',
    messagingSenderId: '173959701132',
    projectId: 'pocket-doctor-b5458',
    databaseURL: 'https://pocket-doctor-b5458-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pocket-doctor-b5458.firebasestorage.app',
    iosBundleId: 'com.example.pocketDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhMSVNIop58coXhZpOS5KdljKgmdhUPQ',
    appId: '1:173959701132:ios:8da34154713a7cea8111a9',
    messagingSenderId: '173959701132',
    projectId: 'pocket-doctor-b5458',
    databaseURL: 'https://pocket-doctor-b5458-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pocket-doctor-b5458.firebasestorage.app',
    iosBundleId: 'com.example.pocketDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApw8WHmdFlCZdiqMVaaSciqtc3RVS51Hc',
    appId: '1:173959701132:web:6b961aab2bb25ba58111a9',
    messagingSenderId: '173959701132',
    projectId: 'pocket-doctor-b5458',
    authDomain: 'pocket-doctor-b5458.firebaseapp.com',
    databaseURL: 'https://pocket-doctor-b5458-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pocket-doctor-b5458.firebasestorage.app',
    measurementId: 'G-KJGZTZS4XD',
  );

}